service: aws-first-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iamRoleStatements: 
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: 
        - arn:aws:dynamodb:us-west-2:123456789012:table/myTable
functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get
  createTask: 
    handler: src/createTask.createTask
    events:
      - httpApi:
          path: /task
          method: post

resources:
  Resources: 
    TaskTable:  
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH