service: aws-first-lambda
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: us-west-2
  iamRoleStatements: 
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: 
        - arn:aws:dynamodb:us-west-2:192474940472:table/TaskTable
functions:
  createTask: 
    handler: src/createTask.createTask
    events:
      - httpApi:
          path: /tasks
          method: post
  getTasks:
    handler: src/getTasks.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get
  getTask:
    handler: src/getTask.getTask
    events: 
      - httpApi: 
          path: /tasks/{id}
          method: get
  putTask: 
    handler: src/putTask.putTask
    events:
      - httpApi:
          path: /tasks
          method: put
  deleteTask:
    handler: src/deleteTask.deleteTask
    events: 
      - httpApi:
          path: /tasks/{id}
          method: delete

resources:
  Resources: 
    TaskTable:  
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH