service: aws-first-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
